# Generated by Django 4.2.5 on 2023-10-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=63, unique=True)),
            ],
            options={
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
                ("photo", models.URLField(max_length=255)),
                ("offer_of_the_month", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=True)),
                ("self_delivery", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        to="goods.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
