# Generated by Django 4.2.5 on 2023-10-03 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["category_name"],
                "verbose_name_plural": "categories",
            },
        ),
    ]
